# Site settings
title: mrwastl's github projects
email: mrwastl (at) users.sourceforge.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  mrwastl
permalink: /:categories/:title.html

# Build settings
#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
timezone: UTC

